In [1]:
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv('/content/Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
data.shape

(10000, 14)

In [4]:
data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [5]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [6]:
import matplotlib.pyplot as plt

In [7]:
X = data.iloc[:,3:13].values
y = data.iloc[:,13].values

In [8]:
type(X)

numpy.ndarray

In [9]:
data.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ct = ColumnTransformer([('encoder', OneHotEncoder(),[1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X),dtype=np.float32)

In [12]:
X[0:10,:]

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.1900000e+02, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.0800000e+02, 4.1000000e+01, 1.0000000e+00,
        8.3807859e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.0200000e+02, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.9900000e+02, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826633e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+0

In [13]:
X = X[:,1:]        #Droping the 1st dummy column for geography
X[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
      dtype=float32)

In [14]:
X = X[:,[0,1,3,4,5,6,7,8,9,10,11]]           #Dropping the column for gender
X.shape

(10000, 11)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [18]:
classifier = Sequential()

In [19]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation='sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 10)

Epoch 1/10
800/800 [==============================] - 15s 1ms/step - loss: 0.5742 - accuracy: 0.7891
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4126 - accuracy: 0.8254
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4073 - accuracy: 0.8178
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3941 - accuracy: 0.8294
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3678 - accuracy: 0.8370
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3671 - accuracy: 0.8394
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3732 - accuracy: 0.8449
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3701 - accuracy: 0.8492
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3732 - accuracy: 0.8431
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3544 - accuracy: 0.858

In [22]:
y_pred = classifier.predict_classes(X_test)
#y_pred = (y_pred > 0.5)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [23]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [24]:
len(y_pred)

2000

In [25]:
list(zip(y_test, y_pred))

[(0, array([0], dtype=int32)),
 (1, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (1, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (0, arr

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1517,   78],
       [ 215,  190]])